/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lx_com_androidjnitest2_ndk_NdkTest */

#ifndef _Included_lx_com_androidjnitest2_ndk_NdkTest
#define _Included_lx_com_androidjnitest2_ndk_NdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lx_com_androidjnitest2_ndk_NdkTest
 * Method:    ndkSayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_lx_com_androidjnitest2_ndk_NdkTest_ndkSayHello
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
